
# GET http://127.0.0.1:5000/hello

# POST http://100.96.56.12:8001/predict
# Content-Type: application/json

# {

#     "MATNR":"MZ-TG-Y240",
#     "KWMENG":11100,
#     "NETPR":18,
#     "KUNNR":"00171",
#     "VKORG": 1710
# }
 



POST http://localhost:4004/odata/v4/quotation/predictQuotation
Content-Type: application/json

{
    "quotation":[
        {
           "KUNNR":"00171",
           "VKORG": "1710",
           "MATNR":"MZ-TG-Y240",
           "NETPR":1,
           "KWMENG":11100
        }
    ]
}


